CompanyApp/Models/Module.cs
using System.ComponentModel.DataAnnotations;

namespace CompanyApp.Models
{
    public class Module
    {
        public int Id { get; set; }
        [Required]
        public string Name { get; set; }
        [Required]
        public string Desctription { get; set; }
        [Required]
        public string Type { get; set; }

        public ICollection<Question> Questions { get; set; }
        public ICollection<ApplicationUser> Users { get; set; }
    }
}

CompanyApp/Controllers/ModulesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using CompanyApp.Data;
using CompanyApp.Models;
using Microsoft.AspNetCore.Authorization;

namespace CompanyApp.Controllers
{
    public class ModulesController : Controller
    {
        private readonly ApplicationDbContext _context;

        public ModulesController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Modules
        [Authorize(Roles = "Admin, Manager")]
        public async Task<IActionResult> Index()
        {
            ViewBag.Completed = new List<int>();
            return View(await _context.Modules.ToListAsync());
        }

        public async Task<IActionResult> UserModules()
        {
            var user = await _context.Users.Include(x => x.Modules).FirstOrDefaultAsync(x => x.UserName == User.Identity.Name);
            ViewBag.Completed = await _context.ModuleUser.Where(x => x.UsersId == user.Id && x.Completed).Select(x => x.ModulesId).ToListAsync();
            return View("Index", user.Modules.ToList());
        }

        // GET: Modules/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Modules == null)
            {
                return NotFound();
            }

            var @module = await _context.Modules
                .FirstOrDefaultAsync(m => m.Id == id);
            if (@module == null)
            {
                return NotFound();
            }

            return View(@module);
        }

        // GET: Modules/Create
        [Authorize(Roles = "Admin, Manager")]
        public IActionResult Create()
        {
            return View();
        }

        // POST: Modules/Create

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin, Manager")]
        public async Task<IActionResult> Create([Bind("Id,Name,Desctription,Type")] Module @module)
        {
            if (ModelState.IsValid)
            {
                _context.Add(@module);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(@module);
        }

        // GET: Modules/Edit/5
        [Authorize(Roles = "Admin, Manager")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Modules == null)
            {
                return NotFound();
            }

            var @module = await _context.Modules.FindAsync(id);
            if (@module == null)
            {
                return NotFound();
            }
            return View(@module);
        }

        // POST: Modules/Edit/5

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin, Manager")]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,Desctription,Type")] Module @module)
        {
            if (id != @module.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(@module);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ModuleExists(@module.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(@module);
        }

        // GET: Modules/Delete/5
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Modules == null)
            {
                return NotFound();
            }

            var @module = await _context.Modules
                .FirstOrDefaultAsync(m => m.Id == id);
            if (@module == null)
            {
                return NotFound();
            }

            return View(@module);
        }

        // POST: Modules/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Modules == null)
            {
                return Problem("Entity set 'ApplicationDbContext.Modules'  is null.");
            }
            var @module = await _context.Modules.FindAsync(id);
            if (@module != null)
            {
                _context.Modules.Remove(@module);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        public IActionResult ShowModuleQuestions(int moduleId)
        {
            var moduleQuestions = _context.Questions.Include(x => x.Module).Where(c => c.Module.Id == moduleId).ToList();
            ViewData["Module"] = _context.Modules.Where(c => c.Id == moduleId).First();
            return View(moduleQuestions);
        }

        [HttpPost]
        public void ShowModuleQuestions(string ModuleId, string Completed)
        {
            bool completed = System.Boolean.Parse(Completed);
            var user = _context.Users.Where(x => x.UserName == User.Identity.Name).FirstOrDefault();
            ModuleUser moduleUser = new ModuleUser()
            {
                UsersId = user.Id,
                ModulesId = int.Parse(ModuleId),
                Completed = completed
            };
            _context.Update(moduleUser);
            _context.SaveChanges();
        }


        private bool ModuleExists(int id)
        {
            return _context.Modules.Any(e => e.Id == id);
        }
    }
}

CompanyApp/Controllers/QuestionsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using CompanyApp.Data;
using CompanyApp.Models;
using Microsoft.AspNetCore.Authorization;

namespace CompanyApp.Controllers
{
    [Authorize(Roles = "Admin, Manager")]

    public class QuestionsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public QuestionsController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Questions
        public async Task<IActionResult> Index()
        {
            return View(await _context.Questions.ToListAsync());
        }

        // GET: Questions/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Questions == null)
            {
                return NotFound();
            }

            var question = await _context.Questions
                .FirstOrDefaultAsync(m => m.Id == id);
            if (question == null)
            {
                return NotFound();
            }

            return View(question);
        }

        // GET: Questions/Create
        public IActionResult Create(int? moduleId = null)
        {
            ViewData["Answer"] = new SelectList(new string[] { Answers.Yes.ToString(), Answers.No.ToString() });
            if (moduleId == null)
            {
                ViewData["ModuleId"] = new SelectList(_context.Modules, "Id", "Name");
            }
            else
            {
                ViewData["ModuleId"] = moduleId;
            }
            return View();
        }

        // POST: Questions/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Description,Answer,ModuleId")] Question question)
        {
            if (ModelState.IsValid)
            {
                _context.Add(question);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(question);
        }

        // GET: Questions/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Questions == null)
            {
                return NotFound();
            }

            var question = await _context.Questions.FindAsync(id);
            if (question == null)
            {
                return NotFound();
            }
            return View(question);
        }

        // POST: Questions/Edit/5

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Description,Answer,IdModule")] Question question)
        {
            if (id != question.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(question);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!QuestionExists(question.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(question);
        }

        // GET: Questions/Delete/5
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Questions == null)
            {
                return NotFound();
            }

            var question = await _context.Questions
                .FirstOrDefaultAsync(m => m.Id == id);
            if (question == null)
            {
                return NotFound();
            }

            return View(question);
        }

        // POST: Questions/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Questions == null)
            {
                return Problem("Entity set 'ApplicationDbContext.Questions'  is null.");
            }
            var question = await _context.Questions.FindAsync(id);
            if (question != null)
            {
                _context.Questions.Remove(question);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool QuestionExists(int id)
        {
            return _context.Questions.Any(e => e.Id == id);
        }
    }
}

CompanyApp/Views/Modules/Create.cshtml
@model CompanyApp.Models.Module

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Module</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Desctription" class="control-label"></label>
                <input asp-for="Desctription" class="form-control" />
                <span asp-validation-for="Desctription" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Type" class="control-label"></label>
                <input asp-for="Type" class="form-control" />
                <span asp-validation-for="Type" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

CompanyApp/Views/Modules/Delete.cshtml
@model CompanyApp.Models.Module

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Module</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Desctription)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Desctription)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Type)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Type)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

CompanyApp/Views/Modules/Details.cshtml
@model CompanyApp.Models.Module

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Module</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Desctription)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Desctription)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Type)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Type)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

CompanyApp/Views/Modules/Edit.cshtml
@model CompanyApp.Models.Module

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Module</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Desctription" class="control-label"></label>
                <input asp-for="Desctription" class="form-control" />
                <span asp-validation-for="Desctription" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Type" class="control-label"></label>
                <input asp-for="Type" class="form-control" />
                <span asp-validation-for="Type" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

CompanyApp/Views/Modules/Index.cshtml
@model IEnumerable<CompanyApp.Models.Module>

@{
    ViewData["Title"] = "Index";
}

<style>
    body {
        background-color: #f2f2f2;
    }

    h1 {
        color: #333;
    }

    table {
        width: 100%;
        border-collapse: collapse;
        background-color: #fff;
        border-radius: 8px;
        box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
    }

    th, td {
        padding: 12px;
        text-align: left;
        border-bottom: 1px solid #f3f3f3;
    }

    th {
        background-color: #8a2be2;
        color: rgba(164,96,255,0.37);
    }

    tr:hover {
        background-color: #f2f2f2; 
    }

    a {
        color: #8a2be2;
    }

        a:hover {
            text-decoration: none;
            color: #5d1aae;
        }
</style>

<h1>My Modules</h1>

<p>
    <a asp-action="Create" style="color: #fff; background-color: #8a2be2; padding: 8px 16px; border-radius: 4px; text-decoration: none;">Create New</a>
</p>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Desctription)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Type)
            </th>
            <th>Completed</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    <a asp-controller="Modules" asp-action="ShowModuleQuestions" asp-route-moduleId="@item.Id">@item.Name</a>
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Desctription)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Type)
                </td>
                <td>
                    @ViewBag.Completed.Contains(item.Id)
                </td>
                <td>
                    <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                    <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                    <a asp-action="Create" asp-controller="Questions" asp-route-moduleId="@item.Id">Add question</a> |
                    <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table>

CompanyApp/Views/Modules/ShowModuleQuestions.cshtml
@model IEnumerable<Question>

<h2 class="d-flex justify-content-center" style="font-weight: bold; margin-bottom:10px;">Модуль: @ViewBag.Module.Name</h2>
<h2 class="d-flex justify-content-center" style="font-weight: bold; margin-bottom:10px;">@ViewBag.Module.Desctription</h2>

<table>
    <tbody id="Users">
        @foreach (var item in Model)
        {
            <tr>
                <th>
                    <label>@item.Description</label>
                    <div>
                        <input type="radio" id="Yes_@item.Id" name="@item.Id" value="@item.Answer" /> Yes
                        <input type="radio" id="No_@item.Id" name="@item.Id" value="@item.Answer" /> No
                    </div>
                </th>
            </tr>
        }
    </tbody>
</table>
<div>
    <a class="btn btn-warning" onclick="SelectList(@ViewBag.Module.Id)">Submit</a>
</div>
<br />
<div id="textField" style="display: none;">
    This is the text that appears when you click the submit button.
</div>

<script>
    function SelectList(moduleId) {
        var commaSeparatedIds = "";
        var totalCount = 0;
        var correctAnswers = 0;
        $("#Users tr input[type=radio]").each(function (index, val) {
            debugger
            totalCount++;
            var checkId = $(val).attr("Id");
            var correctAnswer = $(val).attr("Value");
            var arr = checkId.split('_');

            var IsChecked = $("#" + checkId).is(":checked", true);
            if (IsChecked) {
                if (arr[0] == correctAnswer) {
                    correctAnswers++;
                }
            }
        })

        DisableAllCheckboxes();
        var result = CountResult(totalCount / 2, correctAnswers);

        if (result >= 70) {
            $.ajax({
                async: true,
                url: "/Modules/ShowModuleQuestions",
                type: "POST",
                data: { ModuleId: moduleId, Completed: "True" }
            })
        }
        else{
            $.ajax({
                async: true,
                url: "/Modules/ShowModuleQuestions",
                type: "POST",
                data: { ModuleId: moduleId, Completed: "False" }
            })
        }
    }

    function CountResult(totalCount, correctAnswers) {
        var result = Math.floor((correctAnswers / totalCount) * 100);
        var text = document.getElementById("textField");
        if (result >= 70) {
            text.innerHTML = "You passed. Your result: " + result + "%";
        }
        else {
            text.innerHTML = "You failed. your result: " + result + "%";
        }
        text.style.display = "block";
        return result;
    }

    function DisableAllCheckboxes() {
        for (var inp = document.getElementsByTagName('input'), chb = [], j = 0, J = inp.length; j < J; j++) {
            if (inp[j].type == 'radio') {
                inp[j].disabled = 1;
            }
        }
    }
</script>